### PR TITLE
Fix dependencies and complex editors

### PR DESCRIPTION
**Pull request by davidtwamley**
Working now with editors like RJP.MultiUrlPicker.

Fixes a major dependency oversight. We were only including the dependencies of the property editors but were forgetting to add those datatypes themselves as a dependency too. Fixed.

### CODE REVIEW

**Comment by davidtwamley** [comment]
I started with every permutation I could find here first https://github.com/Lecoati/LeBlender/pull/30. They all almost work but have similar bugs to the ones I've fixed here. I've tested this heavily in my environment and even pulled the before and after json out of the database and diffed it to my satisfaction (there are some annoying differences like `"allowAll": false, "allowed": [...]` not coming over but that's a Courier bug not something we can address in the provider).

Still would be good to get some verification in other environments.

**Comment by clausjensen** [comment]
@davidtwamley Great work! - I'll get it pulled in asap. To be honest I haven't worked much with LeBlender (yet) so testing it beyond the most basic use-cases wasn't something I had much experience in. It's great to get some testing done as there's most likely more usage scenarios I haven't covered.

Now I just need to fix up your formatting and have another look at the changes 😃 

The `"allowAll": false` problem you mention - could you describe that a bit more in detail over here:
http://issues.umbraco.org/issues/COU#newissue

**Comment by clausjensen** [comment]
@davidtwamley Merged in :) Thanks! .. any chance you got around to creating an issue on the `allowAll` problem?

**Comment by davidtwamley** [comment]
Awesome. I just reported it: http://issues.umbraco.org/issue/COU-484

But I am starting to wonder if the issue has more to do with the grid editor saving more json properties than it should--unnecessary stuff that Courier rightfully ignores.

**Pull request merged**
