### PR TITLE
Restructure the dev tree

### PR DESCRIPTION
**Pull request by leekelleher**
- Moved the source-code under a `/src` folder.
- Modified the `AssemblyInfo.cs`, with relevant details and version number (currently set as v0.1.0).
- Set all the assembly references for "Copy Local" to false - this prevents the dependencies being dumped in the output folder.

---

I'm not sure if the VS project/assembly should be called "Umbraco.Courier.Contrib.Resolvers" or "Umbraco.Courier.Contrib.DataResolvers", as that is how they are named within Courier core code?

### CODE REVIEW

**Comment by leekelleher** [comment]
@clausjensen Cool. What are your thoughts on "Resolvers" vs "DataResolvers" assembly/namespacing?

**Comment by clausjensen** [comment]
I'd prefer we keep it resolvers as it really could be any type of resolver going in here - grid cell data, item, propertydata .. all of them will be under the same project.

**Comment by leekelleher** [comment]
OK, cool.

With the folder structure in the VS project now, there's a folder for each package (which is fine). But what I found when I was working on [my other repo](https://github.com/leekelleher/umbraco-courier-dataresolvers/), that there was only one class in each folder and the extra namespacing seemed redundant.

Instead I opted to group them together as "**GridCellDataResolvers**" and "**PropertyDataResolvers**", ([see here](https://github.com/leekelleher/umbraco-courier-dataresolvers/tree/develop/src/Our.Umbraco.Courier.DataResolvers)).  (This follows how [Courier core structures](https://github.com/umbraco/UmbracoDeploy/tree/dev-v7/Contrib/Providers/Umbraco.Courier.DataResolvers) them too).

I'm happy to send a PR for this.

**Comment by clausjensen** [comment]
I'm fine with that change too. I wasn't really sure what would make best sense in terms of structure -- if we would need to add in documentation/assets next to any of these resolvers. But considering the `src` is now in root, any docs/assets should go in a `docs` folder out there anyway.

So yep - it would be great to get rid of those redundant folders 👍

**Pull request merged**
