### PR TITLE
Stacked Content property data-resolver

### PR DESCRIPTION
**Pull request by leekelleher**
Added a property data-resolver for the [Stacked Content property-editor](https://github.com/umco/umbraco-stacked-content).

This includes an abstracted data-resolver for [Inner Content](https://github.com/umco/umbraco-inner-content), (which is the underlying library that powers Stacked Content _and other future property-editors_).

### CODE REVIEW

**Comment by leekelleher** [comment]
A friendly bump on this.  It'd be great (for me) to have StackedContent included in the community bundle.

**Comment by leekelleher** [comment]
Another month passes... and no comment?

**Comment by clausjensen** [comment]
Hi @leekelleher 

This one is merged in now - I've added the fixes from Shannon's PR on NC optimizations (adding some caching) to this resolver as well.

I'm not that familiar with how stacked content stores it's values and what exactly it stores.. but wouldn't the fixes you made for NC (https://github.com/umbraco/Umbraco.Courier.Contrib/pull/28) also have to be applied in a similar fashion to this one ... or is it storing its json in a different way?

**Comment by leekelleher** [comment]
Thanks @clausjensen.

Sure thing, I'll take a look, making sure their logic is aligned. 👍

**Pull request merged**
