### PR TITLE
#50: Set up InnerContentPropertyDataResolver to detect inner content doctype

### PR DESCRIPTION
**Pull request by bowserm**

### CODE REVIEW

**Comment by bowserm** [comment]
This PR is a continuation of this:
https://github.com/umbraco/Umbraco.Courier.Contrib/pull/51

It looks like I was unable to update the old PR and decided to create a new one. I apologize for the confusion this causes.

**Comment by bowserm** [comment]
Looking into this more to try to really understand where it is at. I think I found another place where I need to check for the guid before I check for the alias. Going to do some local testing and make sure I get all of this right. You should hear from me soon.

**Comment by bowserm** [comment]
@clausjensen I updated the pull request. It seemed to be working locally. This is just an update of this PR https://github.com/umbraco/Umbraco.Courier.Contrib/pull/51. Now, the guid will be checked before the alias.

**Comment by nul800sebastiaan** [comment]
Hi there @bowserm, we're writing you today to let you know that Umbraco Courier has entered the security phase earlier this month, as described in the following blog post: [Announcement: Support, LTS and EOL for Umbraco CMS, Cloud and packages](https://umbraco.com/blog/announcement-support-lts-and-eol-for-umbraco-cms-cloud-and-packages/).

This means that we're no longer working on Umbraco Courier issues and in March 2022 we will also stop fixing security issue and Courier is considered EOL (End Of Life) and we no longer recommend using it.

As such, I will be closing this one.

**Pull request closed without merging**
