### PR TITLE
Added support for RJP MultiUrlPickers picking both udis and ids (RJP 2.x.x)

### PR DESCRIPTION
**Pull request by bowserm**
This commit sets up the MultiUrlPickerPropertyDataResolver so that it supports the ids and isMedia properties from RJP.MultiUrlPicker 1.x.x as well as the udi property from RJP.MultiUrlPicker 2.x.x.

Let me know if there is something better I can do with the Pull Request title or with an issue tracker to help this get merged in.

The RJP.MultiUrlPicker JSON looks more like this now:

{{
  "name": "Test Image From Mark - umb logo",
  "udi": "umb://media/a6ce5dbe81c04af6a30ddfee0dbdeee7"
}}

OR

{{
  "name": "Mark's Test 2",
  "udi": "umb://document/f31574ae74b44dc497270f04b437ac06"
}}

### CODE REVIEW

**Comment by bowserm** [comment]
I think the appveyor build errors are unrelated to what I checked in. Please let me know if there is anything I can do to help.

**Comment by p-m-j** [comment]
Yeah appveyor build failed trying to restore Courier.Core, PR #43 should resolve that.

**Comment by bowserm** [comment]
Do you want me to pull down the latest and make a new pull request so it passes appveyor? Or are we good to go?

Thanks!

**Comment by p-m-j** [comment]
My PR hasn't been merged, I just spotted the only other open request and though't I'd check the logs to see if it was because of the issue I was attempting to resolve which it appears to be :)

**Comment by clausjensen** [comment]
@bowserm Thanks for the PR - changes look good so I've pulled it in 👍

**Pull request merged**
